library/book/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('books/', views.all_books, name='all_books'),
    path('books/<int:book_id>/', views.view_book, name='view_book'),
    path('books/filter/', views.filter_books, name='filter_books'),
    path('users/<int:user_id>/', views.user_books, name='user_books'),
    path('books/add/', views.add_book, name='add_book'),
    path('books/edit/<int:book_id>/', views.edit_book, name='edit_book'),
    path('book/<int:book_id>/delete/', views.delete_book, name='delete_book'),
    # path('export/csv/', views.export_books_csv, name='export_books_csv'),
    path('books/analytics/', views.analytics, name='analytics'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

library/library/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('', include('book.urls')),
    path('', include('order.urls')),
    path('', include('support.urls')),
    path('authors/', include('author.urls'))
]

library/book/models.py
from django.db import models


class User(models.Model):
    """
    This class represents a user.
    """
    name = models.CharField(max_length=128)
    email = models.EmailField(unique=True)

    def __str__(self):
        return self.name

    def get_all_books(self):
        """
        Get all books provided to this user.
        """
        return self.books_provided.all()


from django.db import models

class Book(models.Model):
    """
        This class represents a Book.
    """
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=128, blank=True)
    description = models.CharField(max_length=256, blank=True)
    genre = models.CharField(max_length=128, blank=True)
    date_of_issue = models.DateField(null=True, blank=True)
    image = models.ImageField(upload_to='images/', null=True, blank=True)  # Поле для зображення
    isbn = models.CharField(max_length=13, blank=True)  # Поле для ISBN
    authors = models.ManyToManyField('author.Author', related_name='book_authors', blank=True)
    link = models.URLField(max_length=200, blank=True)  # Поле для URL посилання

    def __str__(self):
        """
        Повертає рядок, що описує книгу.
        """
        authors = [author.id for author in self.authors.all()]
        return f"{self.name[:20]}"

    def __repr__(self):
        """
        Повертає текстовий опис об'єкта книги.
        """
        return f"Book(id={self.id})"

    @staticmethod
    def get_by_id(book_id):
        """
        Повертає книгу за її ID.
        """
        return Book.objects.get(id=book_id) if Book.objects.filter(id=book_id) else None

    @staticmethod
    def delete_by_id(book_id):
        """
        Видаляє книгу за її ID.
        """
        if Book.get_by_id(book_id) is None:
            return False
        Book.objects.get(id=book_id).delete()
        return True

    @staticmethod
    def create(name, description, authors=None, link=None):
        """
        Створює нову книгу та додає її до бази даних.
        """
        if len(name) > 128:
            return None

        book = Book()
        book.name = name
        book.description = description
        if authors:
            for elem in authors:
                book.authors.add(elem)
        if link:
            book.link = link
        book.save()
        return book

    def to_dict(self):
        """
        Повертає словник з інформацією про книгу.
        """
        # Implement this method based on your requirements.

    def update(self, name=None, description=None, link=None):
        """
        Оновлює інформацію про книгу.
        """
        if name is not None:
            self.name = name

        if description is not None:
            self.description = description

        if link is not None:
            self.link = link

        self.save()

    def add_authors(self, authors):
        """
        Додає авторів до книги.
        """
        if authors:
            for elem in authors:
                self.authors.add(elem)
                self.save()

    def remove_authors(self, authors):
        """
        Видаляє авторів з книги.
        """
        for elem in authors:
            self.authors.remove(elem)
            self.save()

    @staticmethod
    def get_all():
        """
        Повертає список усіх книг.
        """
        return list(Book.objects.all())

library/book/forms.py
from django.core.validators import MinValueValidator
from django import forms
from .models import Book
from author.models import Author


class BookFilterForm(forms.Form):
    author = forms.CharField(label='Author', required=False)
    genre = forms.CharField(label='Genre', required=False)
    year_of_publication = forms.IntegerField(label='Year of Publication', required=False)


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['name', 'description', 'isbn', 'date_of_publication', 'image', 'authors']

    # Додайте поле для зображення
    image = forms.ImageField(required=False, label='Image')
    authors = forms.ModelMultipleChoiceField(queryset=Author.objects.all(), required=False, label='Authors')

    # # Якщо ви хочете додати валідатор для поля count, ви можете зробити це так
    # count = forms.IntegerField(validators=[MinValueValidator(0)])

library/book/views.py
import codecs
import csv
from django.http import HttpResponse, Http404, HttpResponseNotFound, HttpResponseRedirect
from django import forms
from django.contrib import messages
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.core.validators import MinValueValidator
from django.shortcuts import render, get_object_or_404, redirect
from django.utils.safestring import mark_safe
from authentication.models import CustomUser
from django.urls import reverse
from django.db.models import Count
from .models import Book, User
from django.conf import settings
import os
from django.contrib.auth.decorators import login_required
from django import forms
from .models import Book
from author.models import Author


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['name', 'description', 'isbn', 'date_of_issue', 'image', 'link']

    name = forms.CharField(required=True, widget=forms.TextInput(attrs={'maxlength': '50'}))

    author = forms.ModelChoiceField(
        queryset=Author.objects.all(),
        widget=forms.Select,
        required=True,
        empty_label=None,
        label='Author',
    )

    description = forms.CharField(required=True,
                                  widget=forms.Textarea(attrs={'rows': 5, 'cols': 40, 'css': 'resize:none;'}))
    isbn = forms.CharField(required=True, widget=forms.TextInput(attrs={'maxlength': '13'}))
    date_of_issue = forms.DateField(required=True, widget=forms.SelectDateWidget(years=range(1900, 2024)))

    # Додаємо нове поле `link`
    link = forms.URLField(required=False, widget=forms.URLInput(attrs={'maxlength': '200'}))


@login_required
def all_books(request):
    user_data = request.user.get_user_data()
    search_name = request.GET.get('name')

    if search_name:
        # Ищем книги по названию, содержащему введенную пользователем строку
        books = Book.objects.filter(name__icontains=search_name)
    else:
        # Если строка поиска не указана, отображаем все книги
        books = Book.objects.all()

    # Отримання номера сторінки з параметра запиту
    page = request.GET.get('page')
    paginator = Paginator(books, 10)  # Розділити на сторінки по 20 книг на кожній

    try:
        books = paginator.page(page)
    except PageNotAnInteger:
        # Якщо номер сторінки не є цілим числом, показати першу сторінку.
        books = paginator.page(1)
    except EmptyPage:
        # Якщо номер сторінки за межами доступних сторінок, показати останню сторінку.
        books = paginator.page(paginator.num_pages)

    if not books:
        messages.info(request, "No books available.")

    return render(request, 'book/all_books.html', {'books': books, 'user_data': user_data})


def view_book(request, book_id):
    user_data = request.user.get_user_data()
    book = get_object_or_404(Book, id=book_id)
    return render(request, 'book/view_book.html', {'book': book, 'user_data': user_data})


def filter_books(request):
    name = request.GET.get('name')
    description = request.GET.get('description')
    genre = request.GET.get('genre')

    books = Book.objects.all()

    if name:
        books = books.filter(name__icontains=name)

    if description:
        books = books.filter(description__icontains=description)

    if genre:
        books = books.filter(genre=genre)

    return render(request, 'book/filter_books.html', {'books': books})



def user_books(request, user_id):
    user = get_object_or_404(CustomUser, id=user_id)
    books = user.books.all()
    return render(request, 'book/user_books.html', {'user': user, 'books': books})


from django.shortcuts import get_object_or_404


def add_book(request):
    if request.method == 'POST':
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            book_instance = form.save(commit=False)

            book_instance.save()

            book_id = book_instance.id

            if 'author' in request.POST:
                author_id = request.POST['author']
                author = get_object_or_404(Author, pk=author_id)
                book_instance.authors.add(author)

            if 'link' in request.POST:
                book_instance.link = request.POST['link']
                book_instance.save()

            return redirect('all_books')
    else:
        form = BookForm()
    return render(request, 'book/add_book.html', {'form': form})


def edit_book(request, book_id):
    book = get_object_or_404(Book, id=book_id)
    if request.method == 'POST':
        form = BookForm(request.POST, request.FILES, instance=book)
        if form.is_valid():
            book_instance = form.save(commit=False)
            # Перевірка та збереження поля link
            if 'link' in request.POST:
                book_instance.link = request.POST['link']
                book_instance.save()

            # Обробка зображення
            if 'image' in request.FILES:
                handle_uploaded_image(request.FILES['image'], book_instance)

            book_instance.save()
            return redirect('view_book', book_id=book_id)
    else:
        form = BookForm(instance=book)
    return render(request, 'book/edit_book.html', {'form': form, 'book': book})


def handle_uploaded_image(image, book_instance):
    # Визначте шлях, куди зберегти зображення
    image_path = os.path.join(settings.MEDIA_ROOT, 'images', image.name)
    with open(image_path, 'wb+') as destination:
        for chunk in image.chunks():
            destination.write(chunk)
    book_instance.image = os.path.join('images', image.name)


def delete_book(request, book_id):
    book = get_object_or_404(Book, id=book_id)

    if request.method == 'POST':
        book.delete()
        success_message = f'<div size="5" css="color: white">Book "{book.name}" has been deleted.</div>'
        messages.success(request, mark_safe(success_message))
        return HttpResponseRedirect(reverse('all_books'))

    return render(request, 'book/delete_book.html', {'book': book})


def export_books_csv(request):
    # Устанавливаем тип содержимого для CSV-файла
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="books.csv"'
    response.write(codecs.BOM_UTF8)

    # Создаем писателя CSV
    writer = csv.writer(response)

    # Получаем значения выбранных столбцов из формы запроса
    export_id = request.GET.get('export_id') == 'on'
    export_name = request.GET.get('export_name') == 'on'
    export_description = request.GET.get('export_description') == 'on'
    export_author = request.GET.get('export_author') == 'on'
    export_date_of_issue = request.GET.get('export_date_of_issue') == 'on'

    # Составляем заголовок CSV-файла в зависимости от выбранных столбцов
    header = []
    if export_id:
        header.append('ID')
    if export_name:
        header.append('Name')
    if export_description:
        header.append('Description')
    if export_author:
        header.append('Author')
    if export_date_of_issue:
        header.append('Date of Publication')

    # Записываем заголовок в CSV-файл
    writer.writerow(header)

    # Получаем все книги для экспорта
    books = Book.objects.all()

    for book in books:
        row = []
        if export_id:
            row.append(book.id)
        if export_name:
            row.append(book.name)
        if export_description:
            row.append(book.description)
        if export_author:
            # Получаем всех авторов книги
            authors = book.author.all() if hasattr(book, 'author') else []
            # Объединяем имена и фамилии авторов в одну строку, разделяя запятыми
            author_names = ", ".join(f"{author.name} {author.surname}" for author in authors)
            row.append(author_names)
        if export_date_of_issue:
            row.append(book.date_of_issue)

        # Записываем строку в CSV-файл
        writer.writerow(row)

    # Возвращаем HTTP-ответ с содержимым CSV-файла
    return response


from django.db.models.functions import ExtractYear

# views.py
def analytics(request):
    # Аналітика користувачів
    total_users = User.objects.count()

    # Аналітика книг

    total_books = Book.objects.count()

    # Аналітика за виходом книг з часом
    books_issued_over_time = Book.objects.annotate(year=ExtractYear('date_of_issue')).values('year').annotate(
        total=Count('id'))

    # Аналітика інтеракцій
    books_per_user = {user.name: user.get_all_books().count() for user in User.objects.all()}
    # popular_books = Book.objects.order_by('-count')[:5]

    # Темпоральна аналітика
    # Припустимо, що у книги є поле `date_of_issue`
    books_issued_by_month = Book.objects.extra({'month': "EXTRACT(month FROM date_of_issue)"}).values('month').annotate(
        total=Count('id'))

    # Аналітика по жанрам
    genres_count = Book.objects.values('genre').annotate(total=Count('id'))

    context = {
        'total_users': total_users,
        'total_books': total_books,
        'books_per_user': books_per_user,
        # 'popular_books': popular_books,
        'books_issued_by_month': books_issued_by_month,
        'genres_count': genres_count,
        'total_books': total_books,
        'books_issued_over_time': books_issued_over_time,
    }
    return render(request, 'book/analytics.html', context)

library/book/templates/book/add_book.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Book</title>
    <style>
        * {
            box-sizing: border-box;
        }

        body {
      font-family: Arial, sans-serif;
        background-color: white;
        background-size: cover; /* Розмір фону - вписати весь вікно браузера */
        background-repeat: no-repeat; /* Заборонити повторення фонового зображення */
        background-attachment: fixed; /* Фіксований фон при прокручуванні */
        background-position: center center; /* Вирівнювання фонового зображення по центру */
      }

        .container {
            width: 95%;
            max-width: 800px;
            margin: 0 auto;
            padding: 2rem;
            background-color: #fff;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        h2 {
            color: #333;
            margin-top: 1.5rem;
            margin-bottom: 1rem;
        }

        form {
            margin-bottom: 1rem;
        }

        label {
            font-weight: bold;
        }

        input[type="text"],
        textarea {
            width: 100%;
            padding: 0.5rem;
            margin-bottom: 1rem;
        }

        button {
            padding: 0.5rem 1rem;
            background-color: #4CAF50;
            color: #fff;
            border: none;
            cursor: pointer;
        }

        .return-button {
            display: inline-block;
            padding: 0.5rem 1rem;
            background-color: #4CAF50;
            color: #fff;
            border: none;
            border-radius: 4px;
            text-decoration: none;
            transition: background-color 0.3s ease;
            margin-bottom: 1rem;
        }

        .return-button:hover {
            background-color: #45a049;
        }
    </style>
</head>

<body>
    <div class="container">
        <h2>Add Book</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Add</button>
        </form>
        <a href="/books" class="return-button">Return to Book List</a>
    </div>
</body>

</html>

library/book/templates/book/all_books.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <!-- Підключення Font Awesome CSS (переконайтеся, що ви маєте доступ до Font Awesome) -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>All books</title>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="/auth">Main</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
            {% if user_data.role == "Librarian" %}
                <li class="nav-item">
                    <a class="nav-link" href="/authors">All Authors</a>
                </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link" href="#" style="color: #000000; background-color: #ffffff;
                border-radius: 25px;">All Books</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/all_orders">All favorites</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/support">Support</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/user_profile">User Profile</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/about">About</a>
            </li>
        </ul>
    </div>
</nav>

<style>
    body {
        font-family: Arial, sans-serif;
        background-color: white;
        background-size: cover; /* Розмір фону - вписати весь вікно браузера */
        background-repeat: no-repeat; /* Заборонити повторення фонового зображення */
        background-attachment: fixed; /* Фіксований фон при прокручуванні */
        background-position: center center; /* Вирівнювання фонового зображення по центру */
    }

    /* Стилі для кнопок */
    .btn-primary,
    .btn-success {
        transition: background-color 0.3s ease-in-out;  /* Додаємо перехідний ефект для кольору фону */
    }

    /* Змінюємо кольори при наведенні курсору */
    .btn-primary:hover {
        background-color: purple;  /* Змінюємо колір для btn-primary при наведенні */
    }

    .btn-success:hover {
        background-color: #ba2121;  /* Змінюємо колір для btn-success при наведенні */
    }

    .overlay-block {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-color: rgba(255, 255, 255, 0.8); /* Прозорий білий фон */
        display: none; /* Початково ховаємо блок */
        justify-content: center;
        align-items: center;
        z-index: 999; /* Забезпечте, що цей блок знаходиться над іншими елементами */
    }

    /* Стилі для кнопки у блоку, який буде накладатися */
    .overlay-block button {
        padding: 10px 20px;
        background-color: #4CAF50;
        color: #fff;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

    /* Стилі для основного блоку з контентом */
    .main-content {
        position: relative; /* Щоб забезпечити правильне розташування для абсолютно позиціонованого блоку */
        z-index: 1; /* Забезпечте, що основний контент завжди знаходиться під іншими елементами */
    }

    .ask-question-container {
        position: fixed;
        bottom: 20px;
        right: 20px;
        z-index: 999; /* Переконуємося, що контейнер знаходиться поверх інших елементів */
    }

    .table-light th {
        color: black; /* Цвет текста заголовков таблицы */
        background: #cecece;
    }
</style>
<div class="container" style="margin-top: 80px">
    <form class="search-form" method="GET" action="">
        <input type="text" class="search-input" name="name" placeholder="Search by Name">
        <button type="submit" class="search-button">Search</button>
        {% if invalid_id %}
            <p class="error-message">{{ invalid_id }}</p>
        {% endif %}
    </form>


    <p></p>
    <form class="search-form" method="GET" action="">
        {# Your existing code for the search form #}
        {% if user.is_authenticated %}
            {% if user_data.role == "Librarian" %}
                <a href="/books/add" class="btn btn-primary">Add Book</a>
            {% endif %}
            <a href="/books/analytics" class="btn btn-success">Analytics</a>
            <a href="/books/filter" class="btn btn-primary">Filter Book</a>
<!--            <a href="#" class="btn btn-success" onclick="showOverlay()">Export to CSV</a>-->
        {% endif %}
    </form>

    <!-- Блок, який буде накладатися -->

    <script>
        function closeOverlay() {
            document.getElementById('overlayBlock').style.display = 'none';
        }
    </script>

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    {% if books %}
        <p></p>
    <div class="container">
    <div class="author-list">
        <table class="table-light">
            <thead>
                <tr>
<!--                    <th scope="col">ID</th>-->
                    <th scope="col">Name</th>
                    <th scope="col">Genre</th>
                    <th scope="col">Author</th>
                    <th scope="col">Date of publication</th>
                    {% if user_data.role == "Librarian" %}
                        <th scope="col">Actions</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
    {% for book in books %}
        <tr>
            <td><a href="/books/{{ book.id }}">{{ book.name }}</a></td>
            <td>{{ book.genre }}</td>
            <td>
                {% for author in book.authors.all %}
                    {{ author.name }} {{ author.surname }}{% if not forloop.last %}, {% endif %}
                {% empty %}
                    No authors
                {% endfor %}
            </td>

            <td>{{ book.date_of_issue }}</td>
            {% if user_data.role == "Librarian" %}
                <td>
                    <a href="/books/edit/{{ book.id }}" class="btn btn-warning">
                        <i class="fa fa-edit"></i> Edit
                    </a>

                    <a href="/book/{{ book.id }}/delete" class="btn btn-danger">
                        <i class="fa fa-trash fa-spin"></i> Delete
                    </a>
                </td>
            {% endif %}
        </tr>
    {% empty %}
        <tr>
            <td colspan="6" class="not-found">No books available.</td>
        </tr>
    {% endfor %}
</tbody>
        </table>
        <div class="pagination justify-content-center">
            <form class="form-inline" method="GET" action="">
                {% if books.has_previous %}
                    <a href="?page=1" class="btn btn-secondary">&laquo; first</a>
                    <a href="?page={{ books.previous_page_number }}" class="btn btn-secondary">previous</a>
                {% endif %}

                <span class="current-page">
                    Page
                    <input type="number" name="page" value="{{ books.number }}" class="form-control" style="width: 60px;">
                    of {{ books.paginator.num_pages }}.
                </span>

                {% if books.has_next %}
                    <a href="?page={{ books.next_page_number }}" class="btn btn-secondary">next</a>
                    <a href="?page={{ books.paginator.num_pages }}" class="btn btn-secondary">last &raquo;</a>
                {% endif %}

                <button type="submit" class="btn btn-primary">Go</button>
            </form>
        </div>
    </div>
</div>
    {% else %}
        <p class="not-found">Book not found.</p>
    {% endif %}
</div>

<script>
    function showOverlay() {
        var overlayBlock = document.getElementById('overlayBlock');
        overlayBlock.style.display = 'flex'; // Змінюємо стиль для відображення блоку
    }
</script>

<!-- Контейнер для кнопки "Contact" -->
<div class="ask-question-container">
    <button type="button" class="btn btn-info" data-toggle="modal" data-target="#contactModal">
        Contact Us
    </button>
</div>

<!-- Модальное окно для контакта -->
<div class="modal fade" id="contactModal" tabindex="-1" role="dialog" aria-labelledby="contactModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="contactModalLabel">Contact Us</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <div class="modal-body">
                <!-- Форма для контакта -->
                <form>
                    <div class="form-group">
                        <label for="contactMessage">Your Message:</label>
                        <textarea class="form-control col-2" id="contactMessage" rows="4" style="max-width: 80%;"></textarea>
                    </div>
                </form>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Send Message</button>
            </div>
        </div>
    </div>
</div>

<script>
    jQuery(document).ready(function () {
        document.getElementById('questionForm').addEventListener('submit', function (event) {
            event.preventDefault();

            var questionText = document.getElementById('question').value;

            jQuery.ajax({
                type: 'POST',
                url: '/submit_question',
                data: {
                    'question_text': questionText,
                    csrfmiddlewaretoken: '{{ csrf_token }}'
                },
                success: function (response) {
                    console.log('Question submitted successfully!');
                },
                error: function (error) {
                    console.error('Error submitting question:', error);
                }
            });
        });
    });
</script>

</body>

<!-- Bootstrap JS, Popper.js, і jQuery -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

</html>

library/book/templates/book/edit_book.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Book</title>
    <style>
        * {
            box-sizing: border-box;
        }

        body {
            font-family: Arial, sans-serif;
            background-color: white;
            background-size: cover;
            background-attachment: fixed;
            background-position: center;
            background-repeat: no-repeat;
        }

        .container {
            width: 95%;
            max-width: 800px;
            margin: 0 auto;
            padding: 2rem;
            background-color: #fff;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        h2 {
            color: #333;
            margin-top: 1.5rem;
            margin-bottom: 1rem;
        }

        form {
            margin-bottom: 1rem;
        }

        label {
            font-weight: bold;
        }

        input[type="text"],
        textarea {
            width: 100%;
            padding: 0.5rem;
            margin-bottom: 1rem;
        }

        button[type="submit"] {
            padding: 0.5rem 1rem;
            background-color: #4CAF50;
            color: #fff;
            border: none;
            cursor: pointer;
        }

        button[type="submit"]:hover {
            background-color: #45a049;
        }

        .return-button {
            display: inline-block;
            padding: 0.5rem 1rem;
            background-color: #4CAF50;
            color: #fff;
            border: none;
            border-radius: 4px;
            text-decoration: none;
            transition: background-color 0.3s ease;
            margin-bottom: 1rem;
        }

        .return-button:hover {
            background-color: #45a049;
        }
    </style>
</head>

<body>
    <div class="container">
        <h2>Edit Book</h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}

            <!-- Поле для завантаження зображення -->
<!--            <label for="id_image">Image:</label>-->
<!--            <input type="file" id="id_image" name="image">-->

            <button type="submit">Save</button>
        </form>

        <a href="/books" class="return-button">Return to Book List</a>
    </div>
</body>

</html>

library/book/templates/book/user_books.html
<h2>Books provided to {{ user.name }}</h2>
{% if books %}
    <ul>
    {% for book in books %}
        <li>{{ book.title }}</li>
    {% endfor %}
    </ul>
{% else %}
    <p>No books provided to this user.</p>
{% endif %}